<?php 
/**
 * Implements hook_menu()
 */
function categorias_menu(){

  $items['get/%ctools_js/%'] = array(
    'title' => 'Pagina para uso de ajax',
    'page callback' => '_getContentCat',
    'page arguments' => array(1, 2),
    'access callback' => '_access',
    'access arguments' => array(2)
  );

	return $items;
}

function _access($op) {
  return TRUE;
}


/**
 * Implements hook_block_info()
 */
function categorias_block_info(){
	$blocks["categorias_list"] = array(
		'info' => t("Lista de las Categorias"),
		'cache' => DRUPAL_NO_CACHE
	);
	$blocks["carousel"] = array(
		'info' => t("Home Carousel"),
		'cache' => DRUPAL_NO_CACHE
	);
	$blocks["contenido"] = array(
		'info' => t("Contenido Home"),
		'cache' => DRUPAL_NO_CACHE
	);

	return $blocks;
}

/**
 * Implements hook_block_view()
 */
function categorias_block_view($delta){
	drupal_add_js(drupal_get_path("module","categorias") . "/carousel.js");
	drupal_add_js(drupal_get_path("module","categorias") . "/categorias.js");
	drupal_add_css(drupal_get_path("module","categorias") . "/categorias.css");

	$block = array();
	switch ($delta) {
		case 'categorias_list':
			$categorias = _getCategorias();
			$block["content"] = theme("listCategorias", array('categorias' => $categorias));
			break;
		case 'carousel':
			$nodos = _getContent();
			$block["content"] = theme("carousel", array('nodos' => $nodos));
			break;
		case 'contenido':
			$block["content"] = "<div id='content-categorias'></div>";
			break;
	}
	return $block;
}

/**
 * Funcion que trae todas las categorias.
 * @return categorias array de categorias
 */
function _getCategorias(){

	ctools_include('ajax');
  drupal_add_library('system', 'drupal.ajax');

	$query = db_query("SELECT data.name FROM {taxonomy_term_data} data INNER JOIN {taxonomy_vocabulary} voca ON (data.vid = voca.vid) WHERE voca.machine_name LIKE 'categorias'");

	$categorias = array();
	foreach ($query as $cat) {
		$categorias[] = l($cat->name,'get/nojs/'.$cat->name, array('attributes' => array('class' => array('use-ajax'))));
	}

	return $categorias;
}

/**
 * Funcion que carga los nodos mas recientes
 * @return nodos array de nodos
 */
function _getContent(){
	$query = db_query("SELECT nid FROM {node} WHERE type ='libro' OR type ='medios_electronicos' OR type ='revista' ORDER BY created DESC LIMIT 10");

	$nodos = array();
	foreach ($query as $nid) {
		$nodos[] = node_load($nid->nid);
	}

	return $nodos;
}

/**
 * Implements hook_theme()
 */
function categorias_theme(){
	return array(
		'listCategorias' => array(
			'variables' => array(
				'categorias' => NULL
			),
			'template' => 'list-categorias-block'
		),
		'carousel' => array(
			'variables' => array(
				'nodos' => NULL
			),
			'template' => 'carousel-categorias-block'
		)
	);
}

/**
 * Función que procesa el ajax, y devuelve el contenido segun la categoria.
 *
 * @param bool $js
 *   Indica si la acción es por ajax o no.
 *
 * @param object $cat
 *   Identificador del usuario.
 *
 * @return string
 *   Comandos de Ajax.
 */
function _getContentCat($js, $cat) {
  if ($js) {
    // Si entró aquí, el javascript está habilitado.
    ctools_include('ajax');
 		
 		$query = db_query("SELECT nid FROM {node} WHERE type = :categoria ORDER BY created DESC ", array(":categoria" => $cat));
  	
  	$nodos = array();
		
		foreach ($query as $nid) {
			$nodos[] = node_load($nid->nid);
		}

    $commands = array();

    $variables = array(
      'nodos' => $nodos,
      'html_id' => '#content-categorias',
    );
 
    $commands[] = ajax_command_invoke(NULL, 'cargar_contenido', array(json_encode($variables)));
 
    print ajax_render($commands);
    exit;
  }
  else {
    return print "Hola mundo";

  }
}